# Generated by Django 4.2.9 on 2024-01-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preparation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("ruc", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price_per_gram", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="management.supplier")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shape", models.CharField(choices=[("C", "Circular"), ("R", "Rectangular")], max_length=1)),
                ("dimensions", models.JSONField()),
                (
                    "product_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="management.producttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreparationSupply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_in_grams", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preparation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="management.preparation"),
                ),
                ("supply", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="management.supply")),
            ],
        ),
        migrations.AddField(
            model_name="preparation",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="management.product"),
        ),
        migrations.AddField(
            model_name="preparation",
            name="supplies",
            field=models.ManyToManyField(through="management.PreparationSupply", to="management.supply"),
        ),
    ]
