# Generated by Django 4.2.9 on 2024-01-31 03:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
