# Generated by Django 4.2.9 on 2024-02-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_supplier_created_alter_supplier_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price_per_gram", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="management.supplier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("shape", models.CharField(choices=[("C", "Circular"), ("R", "Rectangular")], max_length=1)),
                ("dimensions", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_in_grams", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ingredient",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="management.ingredient"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="management.recipe"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="preparationsupply",
            name="preparation",
        ),
        migrations.RemoveField(
            model_name="preparationsupply",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shape",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Preparation",
        ),
        migrations.DeleteModel(
            name="PreparationSupply",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="Supply",
        ),
        migrations.AddField(
            model_name="product",
            name="recipe",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="management.recipe"),
        ),
    ]
