# Generated by Django 4.2.9 on 2024-02-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_ingredient_recipe_recipeingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(through="management.RecipeIngredient", to="management.ingredient"),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="management.recipe"),
            preserve_default=False,
        ),
    ]
