# Generated by Django 4.2.9 on 2024-02-20 03:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_recipe_ingredients_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="price_per_gram",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity_in_grams",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$")]
            ),
        ),
    ]
