# Generated by Django 4.2.9 on 2024-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_alter_ingredient_price_per_gram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="dimensions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
