# Generated by Django 4.2.9 on 2024-02-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_remove_recipe_diameter_remove_recipe_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="recipe",
            name="diameter",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="length",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="width",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(),
        ),
    ]
