# Generated by Django 4.2.9 on 2024-02-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0010_remove_recipe_created_at_remove_recipe_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="management.recipe"
            ),
        ),
    ]
